"""revision

Revision ID: 1288ae5f13ea
Revises: d2f7ceb0ace5
Create Date: 2025-01-21 22:33:37.780229

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1288ae5f13ea'
down_revision: str | None = 'd2f7ceb0ace5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('groups_group_leader_id_fkey', 'groups', type_='foreignkey')
    op.drop_column('groups', 'group_leader_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('group_leader_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('groups_group_leader_id_fkey', 'groups', 'students', ['group_leader_id'], ['id'])
    # ### end Alembic commands ###
