"""revision

Revision ID: 1914520029f6
Revises: b79a576a62df
Create Date: 2025-01-30 16:49:49.754346

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1914520029f6'
down_revision: str | None = 'b79a576a62df'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teachers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('middle_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('short_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('short_name'),
    sa.UniqueConstraint('telegram_id'),
    )
    op.add_column('lessons', sa.Column('teacher_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'lessons', 'teachers', ['teacher_id'], ['id'])
    op.drop_column('lessons', 'teacher')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('teacher', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'lessons', type_='foreignkey')
    op.drop_column('lessons', 'teacher_id')
    op.drop_table('teachers')
    # ### end Alembic commands ###
