"""revision

Revision ID: 1d9a83428938
Revises: 81aa754c6e85
Create Date: 2025-01-21 18:28:44.172801

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '1d9a83428938'
down_revision: str | None = '81aa754c6e85'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
