"""revision

Revision ID: 200ef5ca7dbc
Revises: 968fdfd699b2
Create Date: 2025-01-30 17:09:41.840700

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '200ef5ca7dbc'
down_revision: str | None = '968fdfd699b2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
