"""revision

Revision ID: 27473af3062f
Revises: 3fe21bfa68f3
Create Date: 2025-01-30 19:58:27.304931

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '27473af3062f'
down_revision: str | None = '3fe21bfa68f3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
