"""revision

Revision ID: 3fe21bfa68f3
Revises: cd3570c9c3ed
Create Date: 2025-01-30 17:18:46.736479

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '3fe21bfa68f3'
down_revision: str | None = 'cd3570c9c3ed'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
