"""revision

Revision ID: 4e33ea113654
Revises: 1288ae5f13ea
Create Date: 2025-01-21 23:53:44.385586

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4e33ea113654'
down_revision: str | None = '1288ae5f13ea'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groupleaderships', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint('groupleaderships_student_id_fkey', 'groupleaderships', type_='foreignkey')
    op.create_foreign_key(None, 'groupleaderships', 'students', ['user_id'], ['id'])
    op.drop_column('groupleaderships', 'student_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groupleaderships', sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'groupleaderships', type_='foreignkey')
    op.create_foreign_key('groupleaderships_student_id_fkey', 'groupleaderships', 'students', ['student_id'], ['id'])
    op.drop_column('groupleaderships', 'user_id')
    # ### end Alembic commands ###
