"""revision

Revision ID: 4f1769ece89b
Revises: 7fcee94c0c7b
Create Date: 2025-01-25 23:37:05.003656

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '4f1769ece89b'
down_revision: str | None = '7fcee94c0c7b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
