"""revision

Revision ID: 501ce6a1f348
Revises: 78b1de54cbed
Create Date: 2025-01-26 23:23:03.352379

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '501ce6a1f348'
down_revision: str | None = '78b1de54cbed'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
