"""revision

Revision ID: 597ada2cad82
Revises: df8eb437a0e6
Create Date: 2025-01-26 23:35:08.716849

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '597ada2cad82'
down_revision: str | None = 'df8eb437a0e6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
