"""revision

Revision ID: 6eaba8cf98cf
Revises: 7084e1df6920
Create Date: 2025-01-21 14:04:29.764760

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6eaba8cf98cf'
down_revision: str | None = '7084e1df6920'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('studentconfirmations', sa.Column('exist_user', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'studentconfirmations', 'students', ['exist_user'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'studentconfirmations', type_='foreignkey')
    op.drop_column('studentconfirmations', 'exist_user')
    # ### end Alembic commands ###
