"""revision

Revision ID: 78b1de54cbed
Revises: 4f1769ece89b
Create Date: 2025-01-26 22:23:09.216071

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '78b1de54cbed'
down_revision: str | None = '4f1769ece89b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('institute', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'institute')
    # ### end Alembic commands ###
