"""revision

Revision ID: 7fcee94c0c7b
Revises: 4e33ea113654
Create Date: 2025-01-22 00:23:38.948748

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7fcee94c0c7b'
down_revision: str | None = '4e33ea113654'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE groups ALTER COLUMN chat_id TYPE BIGINT USING chat_id::bigint")
    op.create_unique_constraint(None, 'groups', ['chat_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE groups ALTER COLUMN chat_id TYPE VARCHAR USING chat_id::varchar")
    op.drop_constraint(None, 'groups', type_='unique')
    # ### end Alembic commands ###
