"""revision

Revision ID: 81aa754c6e85
Revises: 95ff39979fc2
Create Date: 2025-01-21 18:27:33.020707

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '81aa754c6e85'
down_revision: str | None = '95ff39979fc2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('is_group_leader', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'is_group_leader')
    # ### end Alembic commands ###
