"""revision

Revision ID: 95ff39979fc2
Revises: 6eaba8cf98cf
Create Date: 2025-01-21 17:40:56.044560

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '95ff39979fc2'
down_revision: str | None = '6eaba8cf98cf'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('chat_url', sa.String(), nullable=True))
    op.alter_column('students', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('groups', 'chat_url')
    # ### end Alembic commands ###
