"""revision

Revision ID: 968fdfd699b2
Revises: 1914520029f6
Create Date: 2025-01-30 17:07:57.859770

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '968fdfd699b2'
down_revision: str | None = '1914520029f6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
