"""revision

Revision ID: aaa3a993f8a1
Revises: 501ce6a1f348
Create Date: 2025-01-26 23:34:29.134537

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'aaa3a993f8a1'
down_revision: str | None = '501ce6a1f348'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'groups', ['short_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'groups', type_='unique')
    # ### end Alembic commands ###
