"""revision

Revision ID: ccbc6f42d10a
Revises: 777ec9b88799
Create Date: 2025-01-21 22:01:40.971715

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ccbc6f42d10a'
down_revision: str | None = '777ec9b88799'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('group_leader_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'groups', 'students', ['group_leader_id'], ['id'])
    op.drop_column('students', 'is_group_leader')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('is_group_leader', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.drop_column('groups', 'group_leader_id')
    # ### end Alembic commands ###
