"""revision

Revision ID: cd3570c9c3ed
Revises: 200ef5ca7dbc
Create Date: 2025-01-30 17:09:46.112906

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'cd3570c9c3ed'
down_revision: str | None = '200ef5ca7dbc'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
