"""revision

Revision ID: df8eb437a0e6
Revises: aaa3a993f8a1
Create Date: 2025-01-26 23:34:51.637802

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'df8eb437a0e6'
down_revision: str | None = 'aaa3a993f8a1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
