"""revision

Revision ID: ea4a8e00a0af
Revises: f4718561a2fa
Create Date: 2025-01-21 22:08:18.250214

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'ea4a8e00a0af'
down_revision: str | None = 'f4718561a2fa'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
