"""revision

Revision ID: f4718561a2fa
Revises: ccbc6f42d10a
Create Date: 2025-01-21 22:06:15.889302

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'f4718561a2fa'
down_revision: str | None = 'ccbc6f42d10a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
